= gst-dsd-media-parsers

This is a GStreamer plugin for parsing media files that use DSD container formats.
Currently, DSF and DFF (= DSDIFF) are supported.

Highlights:

* Parser elements support both push and pull modes
* DSF and DFF parsers can parse metadata
* Seeking in both bytes and time format is handled
* Numerous validity and safety checks are performed to detect corrupted media


== Building and installing

gst-dsd-media-parsers uses https://mesonbuild.com[meson] as its build system. Amongst other reasons, this makes
integration with existing GStreamer build setups easier, such as https://gitlab.freedesktop.org/gstreamer/cerbero[Cerbero].

The build was tested with meson 1.11.1, but older versions should be supported as well.

A C++20 capable compiler is required.

Create a build directory for an out-of-tree build:

    make build
    cd build

Now set up the build by running meson:

    meson ..

You might want to look into the `--buildtype=plain` flag if the compiler flags Meson adds are a problem.
This is particularly useful for packagers. https://mesonbuild.com/Quick-guide.html#using-meson-as-a-distro-packager[Read here for more.]

Also, you might be interested in the `-Dprefix` and `-Dlibdir` arguments to control where to install the
resulting binaries. Again, this is particularly useful for packagers.

Finally, build and install the code by running ninja:

    ninja install


== Available GStreamer elements

These are currently available:

* `dsfparse`: DSF format parser, outputs planar DSD
* `dffparse`: DFF format parser, outputs interleaved DSD

All of these have associated typefinders and can be autoplugged by GStreamer's parsebin (and thus decodebin and playbin).
